### ISSUE TITLE
Ambiguity in "gitignore" exercise 

### ISSUE THREAD

**Issue by keivanipchihagh** [1995parham-teaching/git-exercise#1]
The following sentence is a bit ambiguous: "Remove it from **_history_** and write a gitignore"
Does that mean to rewrite the history of the repository? or just remove it and add to .gitignore file?

**Comment by smf8** [comment]
Hi, 
We want the latter. A simple `git rm` is sufficient.

**Comment by keivanipchihagh** [comment]
Thank you (:
